### ISSUE TITLE
Release schedule for 4.0.6

### ISSUE THREAD

**Issue by johnnykv** [zeromq/zeromq4-x#109]
When is the expected release of 4.0.6?

**Comment by hintjens** [comment]
Within a few weeks. Sorry for the delay on this.

**Comment by johnnykv** [comment]
@hintjens Sorry for bumping, but any updates on when 4.0.6 stable will be released?

**Comment by hintjens** [comment]
Sorry for the slow answer on this. I'll slate the release for this month.
