### ISSUE TITLE
FD_SETSIZE set to default value (64) when crosscompiling with mingw

### ISSUE THREAD

**Issue by mditzel** [zeromq/zeromq4-x#117]
FD_SETSIZE is set to 64 when cross-compiling with mingw using cmake. For MSVC the FD_SETSIZE is set to 1024.

**Comment by mditzel** [comment]
Just submitted the PR.

**Comment by hintjens** [comment]
Is this issue also on libzmq?

**Comment by bluca** [comment]
PR was merged and on libzmq it's fixed in a different way since CMakeList has changed, closing
