### ISSUE TITLE
php zeromq extension: Unable to load dynamic library php_zmq.dll

### ISSUE THREAD

**Issue by kirensiva** [zeromq/zeromq4-x#126]
I have XAMPP with PHP Version 5.6.8. I want to install zeromq extension. Tried the following dlls from http://pecl.php.net/package/zmq/1.1.2/windows. Of course I have extension=php_zmq.dll in \xampp\php\php.ini

php_zmq-1.1.2-5.6-nts-vc11-x64
php_zmq-1.1.2-5.6-ts-vc11-x64

php_zmq-1.1.2-5.6-nts-vc11-x86
php_zmq-1.1.2-5.6-ts-vc11-x86

Getting the error

PHP Warning:  PHP Startup: Unable to load dynamic library 
'C:\xampp\php\ext\php_zmq.dll' - %1 is not a valid Win32 application.in 
Unknown on line 0

**Comment by lajosbencz** [comment]
Make sure you have libzmq.dll next to your php.exe

**Comment by andrew-za** [comment]
I finally got it working:
Download the http://pecl.php.net/package/zmq/1.1.2/windows "5.6 Thread Safe (TS) x86" version.

Copy the php_zmq.dll to php/ext directory

Then copy the libzmq.dll to the xamp/ root directory

RESTART apache.

**Comment by bluca** [comment]
Thanks for reporting a solution.

Closing the issue now given there's a solution and it's not related to code in this repository.
