### ISSUE TITLE
vs2008 builds fail with zmq 4.1.4

### ISSUE THREAD

**Issue by JonathanDFletcher** [zeromq/zeromq4-x#148]
VS2008 project fails to build libzmq with "Cannot open include file: stdint.h".  I added a copy of that file to my directory and added it to the include path.

It then failed with "error C3861: if_nametoindex: identifier not found".  I tried the instructions listed for a similar VS2013 problem, and added iphlpapi.lib to the link libs, but that didn't fix the compile problem.

I have seen similar problems posted against 4.1.4.  Will this issue be addressed in the 4.1.x line?

**Comment by bluca** [comment]
Does this happen on libzmq master? If so, could you please open an issue there?

**Comment by minrk** [comment]
I belive this was fixed by https://github.com/zeromq/zeromq4-1/pull/98.

**Comment by bluca** [comment]
Will zeromq4-x build on windows xp as-is, or do we need to backport that fix?

**Comment by minrk** [comment]
I'm not sure, but I think it's okay. This issue refers specifically to 4.1.4, because the breakage was backported to the 4.1 repo (neither 4.1.3 nor 4.1.4 build on XP). I don't believe the problematic patches were applied all the way to 4.0.x.

**Comment by bluca** [comment]
Ok, makes sense, thanks.
@JonathanDFletcher - I'll close for now, if somehow this problem applies to zeromq4-x let us know.
