### ISSUE TITLE
INSTALL direction example doesn't work

### ISSUE THREAD

**Issue by jjpe** [zeromq/zeromq4-x#161]
I'm trying to compile zmq from the source in this repo.

The INSTALL file mentions this as an example:
`./configure CC=c99 CFLAGS=-g LIBS=-lposix`

To me that means I should be able to compile ZMQ using gcc with the C99 standard (even though GitHub marks ZMQ as a C++ project).

When I try to compile on Ubuntu 16.04 LTS, I get:
````
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '1000' is supported by ustar format... yes
checking whether GID '1000' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... (cached) yes
checking for gcc... c99
checking whether the C compiler works... no
configure: error: in `/home/j/repos/zeromq4-1':
configure: error: C compiler cannot create executables
See `config.log' for more details
````

I have attached the [config.log](https://github.com/zeromq/zeromq4-x/files/537230/config.log.txt) that was generated by `configure`.

Any ideas on how to get this working?

**Comment by bluca** [comment]
That's just the autotools default generated install file. CC is your compiler, and c99 probably doesn't exist on your machine.

If you don't know what to use, simply call ```./configure``` without any parameter and the system defaults will be used, which are enough in most cases.

**Comment by jjpe** [comment]
I wasn't aware that autotools generates an INSTALL file, good to know and keep in mind. 

The c99 file does in fact exist. In effect it's just an alias for `gcc -std=c99`, and I've verified it to work. 

Removing the `-lposix` flag does allow ZMQ to compile however. 

I expect that compiling it with c99 will allow the library to be used from C code, which is why I'm trying this. Is that a correct assumption?

**Comment by bluca** [comment]
No you don't need that parameter, the default ```./configure``` is enough. The library exposes a C API in all cases.

**Comment by jjpe** [comment]
Ok in that case I think this issue can be closed. I might open up another one in the future: I'm trying to find out why Linux  Emacs 25 won't load the zmq dynamic lib properly (it all works fine on OS X). But before I can do that, that requires some more debugging since the issue may also be with Emacs. 

Either way, this bug can be closed.
