### ISSUE TITLE
requested PHP extension zmq is missing from your system.

### ISSUE THREAD

**Issue by tisuchi** [zeromq/zeromq4-x#164]
I am using xampp on mac. react/zmq package is required for me. Whenever I want to install, it shows that requested PHP extension zmq is missing from your system.

I have found few solutions to address this issue, however, none of this works for me. Any solution how to fix that issue?

**Comment by bluca** [comment]
This is the PHP repository, please look over there and if you can't find anything in current issues open a new one there: https://github.com/mkoppanen/php-zmq
