### ISSUE TITLE
zmq_msg_recv return int while the type of 'size' parameter of zmq_msg_init_size is 'size_t'

### ISSUE THREAD

**Issue by hnwyllmm** [zeromq/zeromq4-x#168]
in 64bit system, size_t is uint64_t, int is int32_t.
If I send a message with size large than 4G, then I cannot receive it with zmq_msg_recv

**Comment by hnwyllmm** [comment]
Can I use the zmq_msg_size(msg) routine to get the size?
The huge message will transfer through TCP.

**Comment by bluca** [comment]
Yes, it's just the return code that gets truncated, the message will be fine
