### ISSUE TITLE
zeromq-4.0.5 Solaris 11, when libsodium  not in use,  libssp should not be  added.

### ISSUE THREAD

**Issue by damon-atkins** [zeromq/zeromq4-x#98]
libsodium is not part of standard Solaris. However someone may compile it.   libsodium requires libssp  Currently on solaris libssp is added even if libsodium is NOT in  use which cause a compile issue. libssp is also not part of solaris.

Fix only add libssp if libsodium is found.
Only use libsodium if libssp is also found.

solaris)
....cut...
ssp library is required for libsodium on Solaris-like systems 
LDFLAGS="-lssp $LDFLAGS" 

Some extra reading 
http://www.linuxfromscratch.org/hints/downloads/files/ssp.txt

libzmq.so:
        libnsl.so.1 =>   /lib/libnsl.so.1
        libsocket.so.1 =>        /lib/libsocket.so.1
        libstdc++.so.6 =>        /usr/sfw/lib/libstdc++.so.6
        libm.so.2 =>     /lib/libm.so.2
        libgcc_s.so.1 =>         /usr/sfw/lib/libgcc_s.so.1
        libmp.so.2 =>    /lib/libmp.so.2
        libmd.so.1 =>    /lib/libmd.so.1
        libc.so.1 =>     /lib/libc.so.1
libzmq.so.4:
        libnsl.so.1 =>   /lib/libnsl.so.1
        libsocket.so.1 =>        /lib/libsocket.so.1
        libstdc++.so.6 =>        /usr/sfw/lib/libstdc++.so.6
        libm.so.2 =>     /lib/libm.so.2
        libgcc_s.so.1 =>         /usr/sfw/lib/libgcc_s.so.1
        libmp.so.2 =>    /lib/libmp.so.2
        libmd.so.1 =>    /lib/libmd.so.1
        libc.so.1 =>     /lib/libc.so.1

gcc version 3.4.3 (csl-sol210-3_4-20050802)
SunOS XXX 5.11 11.0 i86pc i386 i86pc Solaris

**Comment by jelmd** [comment]
Confirmed, and dueto the brain damaged libtool, passing -Wl,-as-needed e.g. via LDFLAGS has no effect dueto the absolutely dumb arg re-ordering by this "don't use this crap" tool.
